spring:
  datasource:
    druid:
      url: jdbc:mysql://39.97.127.23:3306/laboratory?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: 39.97.127.23
    port: 6379
  data:
    mongodb:
      host: 39.97.127.23
      port: 27017
      database: laboratory
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zj.laboratory
  #打印SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# OSS相关配置信息
aliyun:
  oss:
    endpoint: http://oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    access-key-id:  # 访问身份验证中用到用户标识
    access-key-secret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucket-name: labweapp # oss的存储空间
    view-url: https://labweapp.oss-cn-beijing.aliyuncs.com # 预览url
    max-size: 10 # 最大文件大小，单位M
    upload-dirs: # 上传的目录
      - header
    image-types: # 上传后缀
      - JPG
      - PNG
      - JPEG
      - GIF
# 微信配置
wechat:
  appId:
  appSecret:
  grantType: authorization_code
  loginUrl: https://api.weixin.qq.com/sns/jscode2session
